name: Crawl HTML

on:
  schedule:
    - cron: '0 */6 * * *'   # chạy mỗi 6 tiếng
  workflow_dispatch:         # cho phép chạy thủ công từ giao diện

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Run crawler
      run: python crawl.py

    - name: Commit and push raw.html
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add raw.html
        git commit -m "🤖 Update raw.html" || echo "No changes"
        git push
